### ISSUE TITLE
Update Coneslayer model after tools.luxonis.com bugfix

### ISSUE THREAD

**Issue by mkrupczak3** [luxonis/depthai-model-zoo#26]
Greetings, 

@Erol444 Helped me submit a model I've developed called [Coneslayer](https://github.com/mkrupczak3/Coneslayer) to the luxonis model zoo last December. It's a custom-trained variant of yolov7-tiny which can recognize many common orange traffic cones.

In the time since, [Luxonis has discovered and patched a bug](https://github.com/luxonis/tools/issues/26) with tools.luxonis.com which may significantly improve how the bounding boxes appear when a converted model is run on an Oak-D. I've reconverted the model and updated the Coneslayer GitHub repo

It should be possible to use the newly-converted model with a normal IoU threshold (such as 0.5) instead of 0.1 as well

Here's a link to the update commit:
https://github.com/mkrupczak3/Coneslayer/commit/9c40bb8545fa4937b08945e9ac5f7c33710c5480

**Comment by mkrupczak3** [comment]
Normally I would submit a PR for this kind of update, but the file is hosted remotely by Luxonis. Is there any way your team could apply this patch?

**Comment by mkrupczak3** [comment]
Here's an example of some bad bounding boxes we were getting with the old version of the converted model:

![bad_boxes](https://user-images.githubusercontent.com/25494111/235574790-7b7f3421-389b-4bdd-9f3d-5d49c6ec8f64.png)

**Comment by mkrupczak3** [comment]
The original PR from last December:
https://github.com/luxonis/depthai-model-zoo/pull/18

**Comment by tersekmatija** [comment]
Thanks for reporting. Uploaded the model to our private storage and update the files (xml and model.yml) in the ZOO.
